project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Week 2"
            href: "Hands-on_Exercise/Wk2/HOE_Wk2.qmd"
          - text: "Week 3"
            href: "Hands-on_Exercise/Wk3/HOE_Wk3.qmd"
          - text: "Week 4 & 5"
            href: "Hands-on_Exercise/Wk4/HOE_Wk4.qmd"
          - text: "Week 6"
            href: "Hands-on_Exercise/Wk6/HOE_Wk6.qmd"
      - text: "In-class Exercise"
        menu:
          - text: "Week 1"
            href: "In-class_Exercise/Wk1/ICE_Wk1.qmd"
          - text: "Week 2"
            href: "In-class_Exercise/Wk2/ICE_Wk2.qmd"
          - text: "Week 3"
            href: "In-class_Exercise/Wk3/ICE_Wk3.qmd"
          - text: "Week 4"
            href: "Hands-on_Exercise/Wk4/HOE_Wk4.qmd"
          - text: "Week 5"
            href: "In-class_Exercise/Wk5/ICE_Wk5.qmd"
          - text: "Week 6"
            href: "In-class_Exercise/Wk6/ICE_Wk6.qmd"
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Ex1"
            href: "Take-home_Exercise/TH1/TH_Ex1.qmd"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

