project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Exercise/Wk2/HOE_Wk2.qmd"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Exercise/Wk3/HOE_Wk3.qmd"
      - text: "In-class Exercise"
        menu:
          - text: "In-Class Exercise 1"
            href: "In-class_Exercise/Wk1/ICE_Wk1.qmd"
          - text: "In-Class Exercise 2"
            href: "In-class_Exercise/Wk2/ICE_Wk2.qmd"
          - text: "In-Class Exercise 3"
            href: "In-class_Exercise/Wk3/ICE_Wk3.qmd"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

