<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-01-24">

<title>IS415-GAA - In-Class Exercise 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Exercise/Wk2/HOE_Wk2.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Exercise/Wk3/HOE_Wk3.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Exercise/Wk1/ICE_Wk1.html">
 <span class="dropdown-text">In-Class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Exercise/Wk2/ICE_Wk2.html">
 <span class="dropdown-text">In-Class Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#check-if-install-relevant-packages" id="toc-check-if-install-relevant-packages" class="nav-link active" data-scroll-target="#check-if-install-relevant-packages">Check if / install relevant packages</a></li>
  <li><a href="#import-geospatial-data" id="toc-import-geospatial-data" class="nav-link" data-scroll-target="#import-geospatial-data">Import Geospatial Data</a>
  <ul class="collapse">
  <li><a href="#geoboundaries-data-set" id="toc-geoboundaries-data-set" class="nav-link" data-scroll-target="#geoboundaries-data-set"><strong>GeoBoundaries data set</strong></a></li>
  <li><a href="#nga-data-set" id="toc-nga-data-set" class="nav-link" data-scroll-target="#nga-data-set"><strong>NGA data set</strong></a></li>
  </ul></li>
  <li><a href="#import-aspatial-data" id="toc-import-aspatial-data" class="nav-link" data-scroll-target="#import-aspatial-data">Import Aspatial Data</a></li>
  <li><a href="#convert-aspatial-to-geospatial" id="toc-convert-aspatial-to-geospatial" class="nav-link" data-scroll-target="#convert-aspatial-to-geospatial">Convert Aspatial to Geospatial</a></li>
  <li><a href="#projection-transformation" id="toc-projection-transformation" class="nav-link" data-scroll-target="#projection-transformation">Projection Transformation</a></li>
  <li><a href="#derive-proportion-of-functional-non-functional-water-points" id="toc-derive-proportion-of-functional-non-functional-water-points" class="nav-link" data-scroll-target="#derive-proportion-of-functional-non-functional-water-points">Derive Proportion of Functional &amp; Non Functional Water Points</a></li>
  <li><a href="#combine-geospatial-aspatial-into-simple-feature-data-frame" id="toc-combine-geospatial-aspatial-into-simple-feature-data-frame" class="nav-link" data-scroll-target="#combine-geospatial-aspatial-into-simple-feature-data-frame">Combine Geospatial &amp; Aspatial into simple feature data frame</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">In-Class Exercise 2</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 24, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="check-if-install-relevant-packages" class="level2">
<h2 class="anchored" data-anchor-id="check-if-install-relevant-packages">Check if / install relevant packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tidyverse, funModeling)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="import-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="import-geospatial-data">Import Geospatial Data</h2>
<section id="geoboundaries-data-set" class="level3">
<h3 class="anchored" data-anchor-id="geoboundaries-data-set"><strong>GeoBoundaries data set</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>geoNGA <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">layer =</span> <span class="st">"geoBoundaries-NGA-ADM2"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">26392</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-NGA-ADM2' from data source 
  `/Users/michelle/Desktop/IS415/shelle-mim/IS415-GAA/In-class_Exercise/Wk2/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 774 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2.668534 ymin: 4.273007 xmax: 14.67882 ymax: 13.89442
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(geoNGA, <span class="at">n=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 538408.1 ymin: 116360.7 xmax: 1248985 ymax: 1079710
Projected CRS: Minna / Nigeria Mid Belt
  shapeName Level                    shapeID shapeGroup shapeType
1 Aba North  ADM2 NGA-ADM2-72505758B79815894        NGA      ADM2
2 Aba South  ADM2 NGA-ADM2-72505758B67905963        NGA      ADM2
3    Abadam  ADM2 NGA-ADM2-72505758B57073987        NGA      ADM2
                        geometry
1 MULTIPOLYGON (((548795.5 11...
2 MULTIPOLYGON (((541412.3 12...
3 MULTIPOLYGON (((1248985 104...</code></pre>
</div>
</div>
</section>
<section id="nga-data-set" class="level3">
<h3 class="anchored" data-anchor-id="nga-data-set"><strong>NGA data set</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>NGA <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geospatial/"</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">layer =</span> <span class="st">"nga_admbnda_adm2"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">26392</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `nga_admbnda_adm2' from data source 
  `/Users/michelle/Desktop/IS415/shelle-mim/IS415-GAA/In-class_Exercise/Wk2/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 774 features and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2.668534 ymin: 4.273007 xmax: 14.67882 ymax: 13.89442
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(NGA, <span class="at">n=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3 features and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 538408.1 ymin: 116360.7 xmax: 1248985 ymax: 1079710
Projected CRS: Minna / Nigeria Mid Belt
  Shape_Leng  Shape_Area   ADM2_EN ADM2_PCODE  ADM2_REF ADM2ALT1EN ADM2ALT2EN
1  0.2370744 0.001523921 Aba North   NG001001 Aba North       &lt;NA&gt;       &lt;NA&gt;
2  0.2624772 0.003531104 Aba South   NG001002 Aba South       &lt;NA&gt;       &lt;NA&gt;
3  3.0753158 0.326867840    Abadam   NG008001    Abadam       &lt;NA&gt;       &lt;NA&gt;
  ADM1_EN ADM1_PCODE ADM0_EN ADM0_PCODE       date    validOn validTo
1    Abia      NG001 Nigeria         NG 2016-11-29 2019-04-17    &lt;NA&gt;
2    Abia      NG001 Nigeria         NG 2016-11-29 2019-04-17    &lt;NA&gt;
3   Borno      NG008 Nigeria         NG 2016-11-29 2019-04-17    &lt;NA&gt;
        SD_EN SD_PCODE                       geometry
1  Abia South  NG00103 MULTIPOLYGON (((548795.5 11...
2  Abia South  NG00103 MULTIPOLYGON (((547286.1 11...
3 Borno North  NG00802 MULTIPOLYGON (((1248985 104...</code></pre>
</div>
</div>
</section>
</section>
<section id="import-aspatial-data" class="level2">
<h2 class="anchored" data-anchor-id="import-aspatial-data">Import Aspatial Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>wp_nga <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/WPDEx.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">#clean_country_name</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Nigeria"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write to RDS format</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(wp_nga, <span class="at">file =</span> <span class="st">"data/aspatial/wpa_nga.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="convert-aspatial-to-geospatial" class="level2">
<h2 class="anchored" data-anchor-id="convert-aspatial-to-geospatial">Convert Aspatial to Geospatial</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>wp_nga<span class="sc">$</span>Geometry <span class="ot">=</span> <span class="fu">st_as_sfc</span>(wp_nga<span class="sc">$</span><span class="st">`</span><span class="at">New Georeferenced Column</span><span class="st">`</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wp_nga)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 71
  row_id #sour…¹ #lat_…² #lon_…³ #repo…⁴ #stat…⁵ #wate…⁶ #wate…⁷ #wate…⁸ #wate…⁹
   &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  
1 429068 GRID3      7.98    5.12 08/29/… Unknown &lt;NA&gt;    &lt;NA&gt;    Tapsta… Tapsta…
2 222071 Federa…    6.96    3.60 08/16/… Yes     Boreho… Well    Mechan… Mechan…
3 160612 WaterA…    6.49    7.93 12/04/… Yes     Boreho… Well    Hand P… Hand P…
4 160669 WaterA…    6.73    7.65 12/04/… Yes     Boreho… Well    &lt;NA&gt;    &lt;NA&gt;   
5 160642 WaterA…    6.78    7.66 12/04/… Yes     Boreho… Well    Hand P… Hand P…
6 160628 WaterA…    6.96    7.78 12/04/… Yes     Boreho… Well    Hand P… Hand P…
# … with 61 more variables: `#facility_type` &lt;chr&gt;,
#   `#clean_country_name` &lt;chr&gt;, `#clean_adm1` &lt;chr&gt;, `#clean_adm2` &lt;chr&gt;,
#   `#clean_adm3` &lt;chr&gt;, `#clean_adm4` &lt;chr&gt;, `#install_year` &lt;dbl&gt;,
#   `#installer` &lt;chr&gt;, `#rehab_year` &lt;lgl&gt;, `#rehabilitator` &lt;lgl&gt;,
#   `#management_clean` &lt;chr&gt;, `#status_clean` &lt;chr&gt;, `#pay` &lt;chr&gt;,
#   `#fecal_coliform_presence` &lt;chr&gt;, `#fecal_coliform_value` &lt;dbl&gt;,
#   `#subjective_quality` &lt;chr&gt;, `#activity_id` &lt;chr&gt;, `#scheme_id` &lt;chr&gt;, …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>wp_sf <span class="ot">&lt;-</span> <span class="fu">st_sf</span>(wp_nga, <span class="at">crs=</span><span class="dv">4326</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>wp_sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 95008 features and 70 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 2.707441 ymin: 4.301812 xmax: 14.21828 ymax: 13.86568
Geodetic CRS:  WGS 84
# A tibble: 95,008 × 71
   row_id `#source`      #lat_…¹ #lon_…² #repo…³ #stat…⁴ #wate…⁵ #wate…⁶ #wate…⁷
 *  &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  
 1 429068 GRID3             7.98    5.12 08/29/… Unknown &lt;NA&gt;    &lt;NA&gt;    Tapsta…
 2 222071 Federal Minis…    6.96    3.60 08/16/… Yes     Boreho… Well    Mechan…
 3 160612 WaterAid          6.49    7.93 12/04/… Yes     Boreho… Well    Hand P…
 4 160669 WaterAid          6.73    7.65 12/04/… Yes     Boreho… Well    &lt;NA&gt;   
 5 160642 WaterAid          6.78    7.66 12/04/… Yes     Boreho… Well    Hand P…
 6 160628 WaterAid          6.96    7.78 12/04/… Yes     Boreho… Well    Hand P…
 7 160632 WaterAid          7.02    7.84 12/04/… Yes     Boreho… Well    Hand P…
 8 642747 Living Water …    7.33    8.98 10/03/… Yes     Boreho… Well    Mechan…
 9 642456 Living Water …    7.17    9.11 10/03/… Yes     Boreho… Well    Hand P…
10 641347 Living Water …    7.20    9.22 03/28/… Yes     Boreho… Well    Hand P…
# … with 94,998 more rows, 62 more variables: `#water_tech_category` &lt;chr&gt;,
#   `#facility_type` &lt;chr&gt;, `#clean_country_name` &lt;chr&gt;, `#clean_adm1` &lt;chr&gt;,
#   `#clean_adm2` &lt;chr&gt;, `#clean_adm3` &lt;chr&gt;, `#clean_adm4` &lt;chr&gt;,
#   `#install_year` &lt;dbl&gt;, `#installer` &lt;chr&gt;, `#rehab_year` &lt;lgl&gt;,
#   `#rehabilitator` &lt;lgl&gt;, `#management_clean` &lt;chr&gt;, `#status_clean` &lt;chr&gt;,
#   `#pay` &lt;chr&gt;, `#fecal_coliform_presence` &lt;chr&gt;,
#   `#fecal_coliform_value` &lt;dbl&gt;, `#subjective_quality` &lt;chr&gt;, …</code></pre>
</div>
</div>
</section>
<section id="projection-transformation" class="level2">
<h2 class="anchored" data-anchor-id="projection-transformation">Projection Transformation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform to appropriate projected coordinate system of Nigeria</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>wp_sf <span class="ot">&lt;-</span> wp_sf <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">26392</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="derive-proportion-of-functional-non-functional-water-points" class="level2">
<h2 class="anchored" data-anchor-id="derive-proportion-of-functional-non-functional-water-points">Derive Proportion of Functional &amp; Non Functional Water Points</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get different status of water points</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(wp_sf<span class="sc">$</span><span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA                                 "Functional"                      
[3] "Abandoned/Decommissioned"         "Non-Functional"                  
[5] "Functional but not in use"        "Functional but needs repair"     
[7] "Abandoned"                        "Non functional due to dry season"
[9] "Non-Functional due to dry season"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get functional &amp; non functional water points</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>functional <span class="ot">&lt;-</span> wp_sf <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Functional"</span>) </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>WP_Functional <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(geoNGA, functional))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>non_functional <span class="ot">&lt;-</span> wp_sf <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Non-Functional"</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>WP_Non_Functional <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(geoNGA, non_functional))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(functional)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 45,883
Columns: 71
$ row_id                        &lt;dbl&gt; 222071, 47618, 31962, 48031, 31890, 3347…
$ `#source`                     &lt;chr&gt; "Federal Ministry of Water Resources, Ni…
$ `#lat_deg`                    &lt;dbl&gt; 6.964532, 4.853210, 4.670585, 5.550722, …
$ `#lon_deg`                    &lt;dbl&gt; 3.597668, 6.643272, 7.762312, 6.591315, …
$ `#report_date`                &lt;chr&gt; "08/16/2015 12:00:00 AM", "02/18/2015 12…
$ `#status_id`                  &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "Yes"…
$ `#water_source_clean`         &lt;chr&gt; "Borehole", "Borehole", "Borehole", "Bor…
$ `#water_source_category`      &lt;chr&gt; "Well", "Well", "Well", "Well", "Well", …
$ `#water_tech_clean`           &lt;chr&gt; "Mechanized Pump", "Mechanized Pump", "M…
$ `#water_tech_category`        &lt;chr&gt; "Mechanized Pump", "Mechanized Pump", "M…
$ `#facility_type`              &lt;chr&gt; "Improved", "Improved", "Improved", "Imp…
$ `#clean_country_name`         &lt;chr&gt; "Nigeria", "Nigeria", "Nigeria", "Nigeri…
$ `#clean_adm1`                 &lt;chr&gt; "Ogun", "Rivers", "Akwa Ibom", "Rivers",…
$ `#clean_adm2`                 &lt;chr&gt; "Obafemi-Owode", "Abua/Odual", "Mkpat En…
$ `#clean_adm3`                 &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#clean_adm4`                 &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#install_year`               &lt;dbl&gt; NA, 2009, 2006, 2008, NA, 2009, NA, NA, …
$ `#installer`                  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#rehab_year`                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#rehabilitator`              &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#management_clean`           &lt;chr&gt; "Other", NA, "Community Management", "Ot…
$ `#status_clean`               &lt;chr&gt; "Functional", "Functional", "Functional"…
$ `#pay`                        &lt;chr&gt; "No", "No", "No", "No", "No", "No", "Yes…
$ `#fecal_coliform_presence`    &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#fecal_coliform_value`       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#subjective_quality`         &lt;chr&gt; "Acceptable quality", "Acceptable qualit…
$ `#activity_id`                &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#scheme_id`                  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#wpdx_id`                    &lt;chr&gt; "6FR5XH7X+R37", "6FP8VJ3V+78J", "6FP9MQC…
$ `#notes`                      &lt;chr&gt; "Ajura", "Okana Community", "IKOT EKOP",…
$ `#orig_lnk`                   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#photo_lnk`                  &lt;chr&gt; NA, "https://akvoflow-55.s3.amazonaws.co…
$ `#country_id`                 &lt;chr&gt; "NG", "NG", "NG", "NG", "NG", "NG", "NG"…
$ `#data_lnk`                   &lt;chr&gt; "https://catalog.waterpointdata.org/data…
$ `#distance_to_primary_road`   &lt;dbl&gt; 13364.9005, 17385.9136, 4705.3591, 24565…
$ `#distance_to_secondary_road` &lt;dbl&gt; 48.87743, 18319.56360, 6844.29902, 7300.…
$ `#distance_to_tertiary_road`  &lt;dbl&gt; 4167.5190683, 225.7018842, 1739.1031788,…
$ `#distance_to_city`           &lt;dbl&gt; 13898.649, 41824.663, 43866.546, 49536.0…
$ `#distance_to_town`           &lt;dbl&gt; 9405.7828, 410.1950, 17895.5116, 23861.0…
$ water_point_history           &lt;chr&gt; "{\"2015-08-16\": {\"source\": \"Federal…
$ rehab_priority                &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ water_point_population        &lt;dbl&gt; 140, 1481, 3438, 4436, 1436, 621, 11, 53…
$ local_population_1km          &lt;dbl&gt; 887, 28243, 4568, 9422, 3798, 1110, 6200…
$ crucialness_score             &lt;dbl&gt; 0.157835400, 0.052437772, 0.752626970, 0…
$ pressure_score                &lt;dbl&gt; 0.14000000, 1.48100000, 3.43800000, 4.43…
$ usage_capacity                &lt;dbl&gt; 1000, 1000, 1000, 1000, 1000, 1000, 300,…
$ is_urban                      &lt;lgl&gt; FALSE, TRUE, FALSE, FALSE, FALSE, FALSE,…
$ days_since_report             &lt;dbl&gt; 2592, 2771, 2796, 2763, 2796, 2804, 2773…
$ staleness_score               &lt;dbl&gt; 44.17405, 41.75063, 41.42291, 41.85604, …
$ latest_record                 &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE…
$ location_id                   &lt;dbl&gt; 264633, 219108, 206709, 220770, 206707, …
$ cluster_size                  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ `#clean_country_id`           &lt;chr&gt; "NGA", "NGA", "NGA", "NGA", "NGA", "NGA"…
$ `#country_name`               &lt;chr&gt; "Nigeria", "Nigeria", "Nigeria", "Nigeri…
$ `#water_source`               &lt;chr&gt; "Improved Tube well or borehole", "Impro…
$ `#water_tech`                 &lt;chr&gt; "Motorised", "Motorised", "Motorised", "…
$ `#status`                     &lt;chr&gt; "Functional (and in use)", "Functional (…
$ `#adm2`                       &lt;chr&gt; "Obafemi-Owode", "Abua/Odual", "Mkpat En…
$ `#adm3`                       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#management`                 &lt;chr&gt; "Other", NA, "Community Management", "Ot…
$ `#adm1`                       &lt;chr&gt; "Ogun", "Rivers", "Akwa Ibom", "Rivers",…
$ `New Georeferenced Column`    &lt;chr&gt; "POINT (3.5976683 6.9645317)", "POINT (6…
$ lat_deg_original              &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ lat_lon_deg                   &lt;chr&gt; "(6.9645317°, 3.5976683°)", "(4.85321°, …
$ lon_deg_original              &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ public_data_source            &lt;chr&gt; "https://catalog.waterpointdata.org/data…
$ converted                     &lt;chr&gt; "#status_id, #water_source, #pay, #statu…
$ count                         &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ created_timestamp             &lt;chr&gt; "06/30/2020 12:56:07 PM", "06/30/2020 12…
$ updated_timestamp             &lt;chr&gt; "06/30/2020 12:56:07 PM", "06/30/2020 12…
$ Geometry                      &lt;POINT [m]&gt; POINT (128394.3 330487.9), POINT (…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(non_functional)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 29,385
Columns: 71
$ row_id                        &lt;dbl&gt; 221859, 602018, 602013, 602058, 602009, …
$ `#source`                     &lt;chr&gt; "Federal Ministry of Water Resources, Ni…
$ `#lat_deg`                    &lt;dbl&gt; 7.142345, 6.783210, 6.799595, 6.762375, …
$ `#lon_deg`                    &lt;dbl&gt; 3.375330, 7.604793, 7.615451, 7.659910, …
$ `#report_date`                &lt;chr&gt; "08/07/2015 12:00:00 AM", "10/15/2020 12…
$ `#status_id`                  &lt;chr&gt; "No", "Yes", "Yes", "Yes", "Yes", "Yes",…
$ `#water_source_clean`         &lt;chr&gt; "Piped Water", "Borehole", "Borehole", "…
$ `#water_source_category`      &lt;chr&gt; "Piped Water", "Well", "Well", "Well", "…
$ `#water_tech_clean`           &lt;chr&gt; NA, "Hand Pump - India Mark II", "Hand P…
$ `#water_tech_category`        &lt;chr&gt; NA, "Hand Pump", "Hand Pump", "Hand Pump…
$ `#facility_type`              &lt;chr&gt; "Improved", "Improved", "Improved", "Imp…
$ `#clean_country_name`         &lt;chr&gt; "Nigeria", "Nigeria", "Nigeria", "Nigeri…
$ `#clean_adm1`                 &lt;chr&gt; "Ogun", "Enugu", "Enugu", "Enugu", "Enug…
$ `#clean_adm2`                 &lt;chr&gt; "Obafemi-Owode", "Isi-Uzo", "Udenu", "Is…
$ `#clean_adm3`                 &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#clean_adm4`                 &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#install_year`               &lt;dbl&gt; NA, NA, NA, NA, NA, 2009, NA, NA, NA, NA…
$ `#installer`                  &lt;chr&gt; NA, "WaterAid", "WaterAid", "WaterAid", …
$ `#rehab_year`                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#rehabilitator`              &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#management_clean`           &lt;chr&gt; "Direct Government Operation", NA, NA, N…
$ `#status_clean`               &lt;chr&gt; "Non-Functional", "Non-Functional", "Non…
$ `#pay`                        &lt;chr&gt; "No", "No", "No", "No", "No", "No", "No"…
$ `#fecal_coliform_presence`    &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#fecal_coliform_value`       &lt;dbl&gt; NA, NA, 0, NA, NA, 0, NA, NA, NA, NA, NA…
$ `#subjective_quality`         &lt;chr&gt; "Acceptable quality", "Within National s…
$ `#activity_id`                &lt;chr&gt; NA, "161354372", "161354451", "161354231…
$ `#scheme_id`                  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#wpdx_id`                    &lt;chr&gt; "6FV549RG+W4P", "6FR9QJM3+6W2", "6FR9QJX…
$ `#notes`                      &lt;chr&gt; "Idi Aba", "FROM ABAKPA LIBERTY TO UGWUO…
$ `#orig_lnk`                   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#photo_lnk`                  &lt;chr&gt; "https://akvoflow-55.s3.amazonaws.com/im…
$ `#country_id`                 &lt;chr&gt; "NG", "NG", "NG", "NG", "NG", "NG", "NG"…
$ `#data_lnk`                   &lt;chr&gt; "https://catalog.waterpointdata.org/data…
$ `#distance_to_primary_road`   &lt;dbl&gt; 112.94477, 9885.49199, 7724.57691, 6323.…
$ `#distance_to_secondary_road` &lt;dbl&gt; 2515.7069, 16454.2384, 16639.6899, 20728…
$ `#distance_to_tertiary_road`  &lt;dbl&gt; 296.968839, 65.299696, 455.864295, 16.19…
$ `#distance_to_city`           &lt;dbl&gt; 3656.469, 38630.329, 40716.522, 38809.99…
$ `#distance_to_town`           &lt;dbl&gt; 2795.2586, 24791.2977, 25402.4929, 31303…
$ water_point_history           &lt;chr&gt; "{\"2015-08-07\": {\"photo_lnk\": \"http…
$ rehab_priority                &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ water_point_population        &lt;dbl&gt; NA, 3814, 3723, 572, 2489, 320, 1790, 12…
$ local_population_1km          &lt;dbl&gt; NA, 3880, 7569, 1582, 5032, 677, 15483, …
$ crucialness_score             &lt;dbl&gt; NA, 0.98298969, 0.49187475, 0.36156764, …
$ pressure_score                &lt;dbl&gt; NA, 12.7133333, 12.4100000, 1.9066667, 8…
$ usage_capacity                &lt;dbl&gt; 250, 300, 300, 300, 300, 1000, 1000, 100…
$ is_urban                      &lt;lgl&gt; TRUE, FALSE, FALSE, FALSE, FALSE, FALSE,…
$ days_since_report             &lt;dbl&gt; 2601, 705, 705, 705, 705, 1091, 2687, 26…
$ staleness_score               &lt;dbl&gt; 44.04891, 80.07349, 80.07349, 80.07349, …
$ latest_record                 &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE…
$ location_id                   &lt;dbl&gt; 261864, 220059, 220073, 220048, 220055, …
$ cluster_size                  &lt;dbl&gt; 1, 2, 2, 2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1…
$ `#clean_country_id`           &lt;chr&gt; "NGA", "NGA", "NGA", "NGA", "NGA", "NGA"…
$ `#country_name`               &lt;chr&gt; "Nigeria", "Nigeria", "Nigeria", "Nigeri…
$ `#water_source`               &lt;chr&gt; "Improved Tube well or borehole", "Boreh…
$ `#water_tech`                 &lt;chr&gt; "state water pipe", "India MKII", "India…
$ `#status`                     &lt;chr&gt; "Non-functional Technical breakdown", "N…
$ `#adm2`                       &lt;chr&gt; "Abeokuta South", "Isi-Uzo", "Isi-Uzo", …
$ `#adm3`                       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `#management`                 &lt;chr&gt; "Direct Government Operation", NA, NA, N…
$ `#adm1`                       &lt;chr&gt; "Ogun", "MBU AMON", "ONUAFOR MBA AMON", …
$ `New Georeferenced Column`    &lt;chr&gt; "POINT (3.37533 7.142345)", "POINT (7.60…
$ lat_deg_original              &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ lat_lon_deg                   &lt;chr&gt; "(7.142345°, 3.37533°)", "(6.78321019999…
$ lon_deg_original              &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ public_data_source            &lt;chr&gt; "https://catalog.waterpointdata.org/data…
$ converted                     &lt;chr&gt; "#status_id, #water_source, #pay, #statu…
$ count                         &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ created_timestamp             &lt;chr&gt; "06/30/2020 12:56:07 PM", "09/06/2022 05…
$ updated_timestamp             &lt;chr&gt; "06/30/2020 12:56:07 PM", "09/06/2022 05…
$ Geometry                      &lt;POINT [m]&gt; POINT (103956.4 350486.9), POINT (…</code></pre>
</div>
</div>
<p>Therefore, proportion is 45,883 (functional) : 29,385 (non functional)</p>
</section>
<section id="combine-geospatial-aspatial-into-simple-feature-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="combine-geospatial-aspatial-into-simple-feature-data-frame">Combine Geospatial &amp; Aspatial into simple feature data frame</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>WP_Total <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(geoNGA, wp_sf))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into a tibble</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>nga_combined <span class="ot">&lt;-</span> <span class="fu">tibble</span>(geoNGA, WP_Functional, WP_Total)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>nga_combined <span class="ot">&lt;-</span> nga_combined <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">WP_Functional_Proportion</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">WP_Functional</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">WP_Total</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove NA values</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>nga_combined<span class="sc">$</span><span class="st">`</span><span class="at">WP_Functional_Proportion</span><span class="st">`</span>[<span class="fu">is.na</span>(nga_combined<span class="sc">$</span><span class="st">`</span><span class="at">WP_Functional_Proportion</span><span class="st">`</span>)] <span class="ot">=</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot of total water points</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>nga_combined, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">WP_Total</span><span class="st">`</span>)))<span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>) <span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Total Water Points"</span>,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Number of Water Points"</span>,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of LGAs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ICE_Wk2_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot of functional water points</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>nga_combined, </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">WP_Functional</span><span class="st">`</span>)))<span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Functional Water Points"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Number of Functional Water Points"</span>,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of LGAs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ICE_Wk2_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot of total water points against proportion functional</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>nga_combined, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">WP_Total</span><span class="st">`</span>, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">x=</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">WP_Functional_Proportion</span><span class="st">`</span>)))<span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill=</span><span class="st">"light blue"</span>) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">""</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Proportion of Functional Water Points"</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"Total Water Points"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ICE_Wk2_files/figure-html/unnamed-chunk-17-3.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>