---
title: "Week 2 Exercise"
---

Week 2 Hands-on Exercise

```{r}
pacman::p_load(sf, tidyverse)
```

```{r}
mpsz = st_read(dsn = "data/geospatial", 
                  layer = "MP14_SUBZONE_WEB_PL")
```

Import polyline feature data as shapefile

```{r}
cyclingpath = st_read(dsn = "data/geospatial", 
                         layer = "CyclingPathGazette")

preschool = st_read("data/geospatial/preschools-location.kml")
```

```{r}
# Retrive geometry list-col
st_geometry(mpsz)
```

```{r}
# Display associated attribute info
# Reveals data type of each field
glimpse(mpsz)
```

```{r}
head(mpsz, n=5)
```

Plot, will plot up to a reasonable max by default (in this case 9)

```{r}
plot(mpsz)
```

Plot out only the geometry

```{r}
plot(st_geometry(mpsz))
```

Plot out specific attribute

```{r}
plot(mpsz["PLN_AREA_N"])
```

```{r}
st_crs(mpsz)
```

```{r}
# assign correct EPSG code
mpsz3414 <- st_set_crs(mpsz, 3414)
st_geometry(mpsz3414)
```

```{r}
preschool3414 <- st_transform(preschool, 
                              crs = 3414)
st_crs(preschool3414)
```

```{r}
listings <- read_csv("data/aspatial/listings.csv")
```

```{r}
list(listings) 
```

```{r}
# convert df into simple feature df
# coords arg is c(col name of x coord, col name of y coord)
# crs arg needs coordinates sys in epsg format
# %>%  used to nest st_transform() to transform simple feature data frame into svy21 projected coordinates system
listings_sf <- st_as_sf(listings, 
                       coords = c("longitude", "latitude"),
                       crs=4326) %>%
  st_transform(crs = 3414)
glimpse(listings_sf)
```

```{r}
# Calculate area of cycling paths
buffer_cycling <- st_buffer(cyclingpath, 
                               dist=5, nQuadSegs = 30)
glimpse(buffer_cycling)
buffer_cycling$AREA <- st_area(buffer_cycling)
glimpse(buffer_cycling$AREA)
sum(buffer_cycling$AREA)
```

```{r}
# find numbers of pre-schools in each planning subzone
# st_intersects indentified schools located inside planning subzones
# length() calculate num in each zone
mpsz3414$`PreSch Count`<- lengths(st_intersects(mpsz3414, preschool3414))
summary(mpsz3414$`PreSch Count`)
```

```{r}
# list planning zubzone with most um of pre-school
top_n(mpsz3414, 1, `PreSch Count`)
```

```{r}
glimpse(mpsz3414)
```

```{r}
# Calc density of pre-school by planning subzone
mpsz3414$Area <- mpsz3414 %>%
  st_area()
mpsz3414 <- mpsz3414 %>%
  mutate(`PreSch Density` = `PreSch Count`/Area * 1000000)
head(mpsz3414)
```

```{r}
hist(mpsz3414$`PreSch Density`)

ggplot(data=mpsz3414, 
       aes(x= as.numeric(`PreSch Density`)))+
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue") +
  labs(title = "Are pre-school even distributed in Singapore?",
       subtitle= "There are many planning sub-zones with a single pre-school, on the other hand, \nthere are two planning sub-zones with at least 20 pre-schools",
      x = "Pre-school density (per km sq)",
      y = "Frequency")

ggplot(data=mpsz3414, 
       aes(y = `PreSch Count`, 
           x= as.numeric(`PreSch Density`)))+
  geom_point(color="black", 
             fill="light blue") +
  xlim(0, 40) +
  ylim(0, 40) +
  labs(title = "",
      x = "Pre-school density (per km sq)",
      y = "Pre-school count")
```
